#ifndef WALLET_SETTINGWIN_H
#define WALLET_SETTINGWIN_H

#include "settings.h"

typedef enum {
    SCREEN_SAVER_TIME_15S = 0,
    SCREEN_SAVER_TIME_30S,
    SCREEN_SAVER_TIME_45S,
    SCREEN_SAVER_TIME_60S,
    SCREEN_SAVER_TIMER_MAX
} SCREEN_SAVER_TIME;

typedef enum {
    BRIGHTNESS_LEVEL_1 = 0,
    BRIGHTNESS_LEVEL_2,
    BRIGHTNESS_LEVEL_3,
    BRIGHTNESS_LEVEL_MAX
} BRIGHTNESS_LEVEL;

typedef enum {
    BT_LEVEL_1 = 0,
    BT_LEVEL_2,
    BT_LEVEL_MAX
} BLUETOOTH_LEVEL;


//0 is max
#define BRIGHTNESS_LEVEL_1_VALUE 1
#define BRIGHTNESS_LEVEL_2_VALUE 3
#define BRIGHTNESS_LEVEL_3_VALUE 5

typedef enum {
    RANDOM_PIN_KEYPAD_ON = 0,
    RANDOM_PIN_KEYPAD_OFF,
    RANDOM_PIN_KEYPAD_MAX
} RANDOM_PIN_KEYPAD;

enum {
    SETTING_ITEM_PASSPHRASE = 0,
    SETTING_ITEM_VERIFY,
    SETTING_ITEM_SCREEN_OFF,
    SETTING_ITEM_AUTO_SHUTDOWN,
    SETTING_ITEM_BLUETOOTH,
    SETTING_ITEM_BRIGHTNESS_LEVEL,
    SETTING_ITEM_CHANGE_PASSWD,
    SETTING_ITEM_COINS_SHOW_MANAGER,
    SETTING_ITEM_CHANGE_LANG,
    SETTING_ITEM_RANDOM_PIN_KEYPAD,
    SETTING_ITEM_UPDATE_FIRMWARE,
    SETTING_ITEM_FRESET,
    SETTING_ITEM_DOWNLOAD_APP,
    SETTING_ITEM_ABOUT,
    SETTING_ITEM_MAXID
};

int showDownloadApp();

int showAboutWallet(void);

int SettingWin(void);

#endif
