#ifndef WALLET_PLAT_CONFIG_H
#define WALLET_PLAT_CONFIG_H

#define DEVICE_CPUID_LEN 32

#define CONFIG_SUPPORT_USB_POWER
#define CONFIG_HAVE_BATTERY

#define SECHIP_APP_VERSION 10001
#define SECHIP_DEVICE_TYPE 0x2
#define CONFIG_DETECT_HW_BREAK

#endif

